# to avoid hydra warnings
hydra:
  output_subdir: null # no hydra outputs/ dir

project_name: zero-shot-nvs
run_name: debug_dss1_allparams_50_6
# to be able to quickly clean the project and delete debug runs
tags:
  - allparams
  - debug
  - optimizer

# load config files from the following paths
defaults:
  - _self_
  - datamodule: defaults
  - model: defaults
  - trainer: defaults
  - logger: defaults
